spring:
  application:
    name: api-gateway
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
          - Path=/user/**
